COPY Income_Statement(stock_symbol,company_name,date,revenues,revenue_growth,cost_of_revenue,gross_profit,research_and_development_expense,selling_general_and_administrative_expense,operating_expenses,operating_income,interest_expense,earnings_before_tax,income_tax_expense,net_income_to_noncontrolling_interests,net_income_from_discontinued_operations,net_income,preferred_dividends_income_statement_impact,net_income_common_stock,earnings_per_basic_share,earnings_per_diluted_share,weighted_average_shares,weighted_average_shares_diluted,dividends_per_basic_common_share,gross_margin,ebitda_margin,ebit_margin,profit_margin,free_cash_flow_margin,ebitda,ebit,consolidated_income)
FROM
	'/Users/alstonhsu/projects/financial_reports/amazon.csv'
DELIMITER ',' CSV HEADER;

COPY Income_Statement(stock_symbol,company_name,date,revenues,revenue_growth,cost_of_revenue,gross_profit,research_and_development_expense,selling_general_and_administrative_expense,operating_expenses,operating_income,interest_expense,earnings_before_tax,income_tax_expense,net_income_to_noncontrolling_interests,net_income_from_discontinued_operations,net_income,preferred_dividends_income_statement_impact,net_income_common_stock,earnings_per_basic_share,earnings_per_diluted_share,weighted_average_shares,weighted_average_shares_diluted,dividends_per_basic_common_share,gross_margin,ebitda_margin,ebit_margin,profit_margin,free_cash_flow_margin,ebitda,ebit,consolidated_income)
FROM
	'/Users/alstonhsu/projects/financial_reports/apple.csv'
DELIMITER ',' CSV HEADER;

COPY Income_Statement(stock_symbol,company_name,date,revenues,revenue_growth,cost_of_revenue,gross_profit,research_and_development_expense,selling_general_and_administrative_expense,operating_expenses,operating_income,interest_expense,earnings_before_tax,income_tax_expense,net_income_to_noncontrolling_interests,net_income_from_discontinued_operations,net_income,preferred_dividends_income_statement_impact,net_income_common_stock,earnings_per_basic_share,earnings_per_diluted_share,weighted_average_shares,weighted_average_shares_diluted,dividends_per_basic_common_share,gross_margin,ebitda_margin,ebit_margin,profit_margin,free_cash_flow_margin,ebitda,ebit,consolidated_income)
FROM
	'/Users/alstonhsu/projects/financial_reports/google.csv'
DELIMITER ',' CSV HEADER;

COPY Income_Statement(stock_symbol,company_name,date,revenues,revenue_growth,cost_of_revenue,gross_profit,research_and_development_expense,selling_general_and_administrative_expense,operating_expenses,operating_income,interest_expense,earnings_before_tax,income_tax_expense,net_income_to_noncontrolling_interests,net_income_from_discontinued_operations,net_income,preferred_dividends_income_statement_impact,net_income_common_stock,earnings_per_basic_share,earnings_per_diluted_share,weighted_average_shares,weighted_average_shares_diluted,dividends_per_basic_common_share,gross_margin,ebitda_margin,ebit_margin,profit_margin,free_cash_flow_margin,ebitda,ebit,consolidated_income)
FROM
	'/Users/alstonhsu/projects/financial_reports/ibm.csv'
DELIMITER ',' CSV HEADER;

COPY Income_Statement(stock_symbol,company_name,date,revenues,revenue_growth,cost_of_revenue,gross_profit,research_and_development_expense,selling_general_and_administrative_expense,operating_expenses,operating_income,interest_expense,earnings_before_tax,income_tax_expense,net_income_to_noncontrolling_interests,net_income_from_discontinued_operations,net_income,preferred_dividends_income_statement_impact,net_income_common_stock,earnings_per_basic_share,earnings_per_diluted_share,weighted_average_shares,weighted_average_shares_diluted,dividends_per_basic_common_share,gross_margin,ebitda_margin,ebit_margin,profit_margin,free_cash_flow_margin,ebitda,ebit,consolidated_income)
FROM
	'/Users/alstonhsu/projects/financial_reports/intel.csv'
DELIMITER ',' CSV HEADER;

COPY Income_Statement(stock_symbol,company_name,date,revenues,revenue_growth,cost_of_revenue,gross_profit,research_and_development_expense,selling_general_and_administrative_expense,operating_expenses,operating_income,interest_expense,earnings_before_tax,income_tax_expense,net_income_to_noncontrolling_interests,net_income_from_discontinued_operations,net_income,preferred_dividends_income_statement_impact,net_income_common_stock,earnings_per_basic_share,earnings_per_diluted_share,weighted_average_shares,weighted_average_shares_diluted,dividends_per_basic_common_share,gross_margin,ebitda_margin,ebit_margin,profit_margin,free_cash_flow_margin,ebitda,ebit,consolidated_income)
FROM
	'/Users/alstonhsu/projects/financial_reports/microsoft.csv'
DELIMITER ',' CSV HEADER;
